![](https://img.arctee.cn/qiniu_picgo/DV01-Numpy2.png)

# NumPy 库

**数据维度表示**
- 一维数据：列表或集合类型  
- 二维数据：列表  
- 多维数据：列表 

**数据格式**  
- JSON
- XML
- YAML

In [2]:
# 导入NumPy库
import numpy as np

In [3]:
# 计算 a + b
#原始方式
a = [1, 2, 3, 4]
b = [9, 8, 7, 6]
c = []
for i in range(len(a)):
    c.append(a[i]**2 + b[i]**2)
print(c)

[82, 68, 58, 52]


In [5]:
# 计算 a + b
# numpy实现
a = np.array([1, 2, 3, 4])
b = np.array([9, 8, 7, 6])
c = a**2 + b**2
print(c)

[82 68 58 52]


综上，
- 数组对象可以去掉元素间运算所需的循环，使一维向量更像单个数据（向量化）
- 设置专门的数组对象，经过优化，可以提升这类应用的运算速度（提升运算速度）

## ndarray对象属性
- .ndim：秩，即轴的数量或维度的数量
- .shape：ndarray对象的尺度，对于矩阵，n行m列
- .size：ndarray对象元素的个数，相当于.shape中n*m的值
- .dtype：ndarray对象的元素类型
- .itemsize：ndarray对象中每个元素的大小，以字节为单位

In [7]:
a = np.array([[0, 1, 2, 3, 4],
             [9, 8, 7, 6, 5]])

In [9]:
a.shap  e

(2, 5)

In [11]:
a.size

10

## 创建 ndarray
- 从Python中的列表、元组等类型创建ndarray数组
- 使用NumPy中函数创建ndarray数组，如：arange, ones, zeros等
    - np.arange(n)：元素从0到n‐1
    - np.ones(shape)：生成一个全1数组，shape是元组类型
    - np.zeros(shape)
    - np.full(shape,val)：根据shape生成一个数组，每个元素值都是val
    - np.eye(n)：创建一个正方的n*n单位矩阵，对角线为1，其余为0
- 从字节流（raw bytes）中创建ndarray数组
- 从文件中读取特定格式，创建ndarray数组

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.full((3, 4), 6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

- np.ones_like(a) 根据数组a的形状生成一个全1数组
- np.zeros_like(a) 根据数组a的形状生成一个全0数组
- np.full_like(a,val) 根据数组a的形状生成一个数组，每个元素值都是val

In [19]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
np.ones_like(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- np.linspace() 根据起止数据等间距地填充数据，形成数组(等分）
- np.concatenate() 将两个或多个数组合并成一个新的数组

In [22]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

## ndarray 数组的变换
- .reshape(shape) 不改变数组元素，返回一个shape形状的数组，原数组不变
- .resize(shape) 与.reshape()功能一致，但修改原数组
- .swapaxes(ax1,ax2) 将数组n个维度中两个维度进行调换
- .flatten() 对数组进行降维，返回折叠后的一维数组，原数组不变

In [24]:
a = np.ones((2, 3, 4), dtype=np.int32)
print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [26]:
a.reshape((3, 8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [27]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [28]:
a.resize((3, 8))

In [29]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
a.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

- new_a = a.astype(new_type)：类型变换
- ls = a.tolist()：转换为列表

In [32]:
b = a.astype(np.float)
b

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [35]:
a.tolist()

[[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]

## ndarray 数组的操作
- 索引：获取数组中特定位置元素的过程
- 切片：获取数组元素子集的过程

In [38]:
a = np.arange(24).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
a[1, 2, 3]

23

In [40]:
a[:, 1, -3]

array([ 5, 17])

In [43]:
a[:, 1:3, :]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
a[:, :, ::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

## ndarray数组的运算

- 数组与标量之间的运算作用于数组的每一个元素

In [45]:
a = np.arange(24).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
a.mean()

11.5

In [48]:
a = a / a.mean()
a

array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
        [0.34782609, 0.43478261, 0.52173913, 0.60869565],
        [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],

       [[1.04347826, 1.13043478, 1.2173913 , 1.30434783],
        [1.39130435, 1.47826087, 1.56521739, 1.65217391],
        [1.73913043, 1.82608696, 1.91304348, 2.        ]]])

### 一元函数
- np.abs(x) np.fabs(x) 计算数组各元素的绝对值
- np.sqrt(x) 计算数组各元素的平方根
- np.square(x) 计算数组各元素的平方
- np.log(x) np.log10(x) np.log2(x) 计算数组各元素的自然对数、10底对数和2底对数
- np.ceil(x) np.floor(x) 计算数组各元素的ceiling值或floor值
- np.rint(x) 计算数组各元素的四舍五入值
- np.modf(x) 将数组各元素的小数和整数部分以两个独立数组形式返回
- np.cos(x) np.cosh(x) np.sin(x) np.sinh(x) np.tan(x) np.tanh(x) 计算数组各元素的普通型和双曲型三角函数
- np.exp(x) 计算数组各元素的指数值
- np.sign(x) 计算数组各元素的符号值，1(+), 0, ‐1(‐)

In [50]:
a = np.arange(24).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [51]:
np.square(a)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]], dtype=int32)

In [52]:
np.sqrt(a)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])

In [53]:
np.exp(a)

array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
        [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]],

       [[1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
        [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08],
        [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09]]])

### 二元函数
- \+ ‐ * / ** 两个数组各元素进行对应运算
- np.maximum(x,y) np.fmax()
- np.minimum(x,y) np.fmin() 元素级的最大值/最小值计算
- np.mod(x,y) 元素级的模运算
- np.copysign(x,y) 将数组y中各元素值的符号赋值给数组x对应元素
- \> < >= <= == != 算术比较，产生布尔型数组

**小结**
![](https://img.arctee.cn/qiniu_picgo/DV01-Numpy1.png)